### ISSUE TITLE
FEAT: 신분증 OCR 인식 및 데이터 자동 저장 API 구현

### ISSUE THREAD

**Issue by dalcheonroadhead** [sesac-dev/docs-helper#2]
## ✒ Description

Clovar Template OCR api를 이용한 신분증 정보 저장 

## ✅ Todo
- [x] (1) Clova OCR AI에 신분증 템플릿 사전 학습 시키기
- [x] (2) Clova OCR AI가 신분증을 제대로 인식하는지, 샘플 심분증으로 테스트 (S3, PostMan) 
- [x] (3) Clova OCR API를 활용한 신분증 인식 API 구현 
- [x] (4) 테스트 및 보완
