### ISSUE TITLE
FEAT: 외국인 출입 신고서 번역용, 입력용 템플릿 좌표 추출 API 구현

### ISSUE THREAD

**Issue by dalcheonroadhead** [sesac-dev/docs-helper#3]
## ✒ Description

외국인들의 서류를 번역해주기 위해, 질문들이 적힌 부분의 좌표와, 입력해야할 빈칸 부분 좌표를 추출해서 따로 구분해서 관리한다.

## ✅ Todo
- [ ] (1) 외국인 신고서 빈칸 좌표 추출 (26칸)
- [ ] (2) 팀원들에게 알리기 및 DB에 저장
- [ ] (3) 외국인 신고서 질문칸 좌표 추출 (26칸) 
- [ ] (4) 팀원들에게 알리기 및 DB에 저장 
- [ ] (5) 새로운 서류 인식을 위한 API 구현 (S3, SpringBoot)
